name: apst
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - jupyterlab_rise
  - rise
  - keras
  - matplotlib
  - nbclassic
  - numpy
  - pandas
  - pip
  - python=3.12
  - scipy
  - statsmodels
  - tensorflow
